export enum DisplayCategory {
  LIGHT = 'LIGHT',
  THERMOSTAT = 'THERMOSTAT',
  OTHER = 'OTHER',
  SMARTLOCK = 'SMARTLOCK',
  SCENE_TRIGGER = 'SCENE_TRIGGER',
  ACTIVITY_TRIGGER = 'ACTIVITY_TRIGGER',
  CAMERA = 'CAMERA',
  SWITCH = 'SWITCH',
  TV = 'TV'
}
