export enum HeaderName {
  DISCOVER = 'Discover',
  DISCOVER_RESPONSE = 'Discover.Response',
  TURN_ON = 'TurnOn',
  TURN_OFF = 'TurnOff',
  ADJUST_BRIGHTNESS = 'AdjustBrightness',
  SET_BRIGHTNESS = 'SetBrightness',
  ADJUST_VOLUME = 'AdjustVolume',
  SET_VOLUME = 'SetVolume',
  SET_MUTE = 'SetMute',
  CHANGE_CHANNEL = 'ChangeChannel',
  SKIP_CHANNELS = 'SkipChannels',
  REPORT_STATE = 'ReportState',
  STATE_REPORT = 'StateReport',
  RESPONSE = 'Response',
  ACCEPT_GRANT = 'AcceptGrant',
  ACCEPT_GRANT_RESPONSE = 'AcceptGrant.Response',
  ERROR_RESPONSE = 'ErrorResponse',
  SET_TARGET_TEMPERATURE = 'SetTargetTemperature',
  ADJUST_TARGET_TEMPERATURE = 'AdjustTargetTemperature',
  SET_THERMOSTAT_MODE = 'SetThermostatMode',
  RESUME_SCHEDULE = 'ResumeSchedule'
}
